/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digielancer.component;

/**
 *
 * @author ASUS
 */
public class addBoard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addBoard.class.getName());
    private int projectId;
    private int boardIdToEdit = 0;
    private ProjectManagement parentBoard;

    /**
     * Creates new form addTask
     */
    public addBoard() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        ((javax.swing.text.AbstractDocument) judulField.getDocument()).setDocumentFilter(new LengthLimitFilter(30));
        ((javax.swing.text.AbstractDocument) deskripsiField.getDocument()).setDocumentFilter(new LengthLimitFilter(80));
    }

    public addBoard(java.awt.Frame parent, boolean modal, int projectId, ProjectManagement parentBoard) {
        initComponents();
        this.projectId = projectId;
        this.parentBoard = parentBoard;
        setAlwaysOnTop(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        ((javax.swing.text.AbstractDocument) judulField.getDocument()).setDocumentFilter(new LengthLimitFilter(30));
        ((javax.swing.text.AbstractDocument) deskripsiField.getDocument()).setDocumentFilter(new LengthLimitFilter(80));
    }

    public addBoard(java.awt.Frame parent, boolean modal, int projectId, int boardIdToEdit, ProjectManagement parentBoard) {
        initComponents();
        this.projectId = projectId;
        this.boardIdToEdit = boardIdToEdit;
        this.parentBoard = parentBoard;
        setAlwaysOnTop(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        ((javax.swing.text.AbstractDocument) judulField.getDocument()).setDocumentFilter(new LengthLimitFilter(30));
        ((javax.swing.text.AbstractDocument) deskripsiField.getDocument()).setDocumentFilter(new LengthLimitFilter(80));

        if (boardIdToEdit > 0) {
            jLabel1.setText("Edit Board");
            jButton1.setText("Perbarui Board");
            
            digielancer.model.BoardModel board = digielancer.model.TaskDAO.getBoardById(boardIdToEdit);
            if (board != null) {
                judulField.setText(board.getBoardName());
                deskripsiField.setText(board.getDescription());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        judulField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        deskripsiField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Board Baru");
        jLabel1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N

        judulField.setBackground(new java.awt.Color(248, 250, 252));
        judulField.addActionListener(this::judulFieldActionPerformed);

        jButton1.setText("Simpan Board");
        jButton1.setBackground(new java.awt.Color(6, 141, 240));
        jButton1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        deskripsiField.setBackground(new java.awt.Color(248, 250, 252));

        jLabel2.setText("Judul Board");
        jLabel2.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N

        jLabel3.setText("Deskripsi Board");
        jLabel3.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(deskripsiField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deskripsiField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String title = judulField.getText().trim();
        String desc = deskripsiField.getText().trim();

        if (title.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama board tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean success;
        if (boardIdToEdit > 0) {
            success = digielancer.model.TaskDAO.editBoard(boardIdToEdit, title, desc);
        } else {
            success = digielancer.model.TaskDAO.addBoard(projectId, title, desc);
        }

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, boardIdToEdit > 0 ? "Board berhasil diperbarui!" : "Board baru berhasil ditambahkan!");
            if (parentBoard != null) {
                parentBoard.loadBoard(projectId);
            }
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan board ke database.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void judulFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addBoard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deskripsiField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField judulField;
    // End of variables declaration//GEN-END:variables

    private static class LengthLimitFilter extends javax.swing.text.DocumentFilter {
        private final int limit;
        public LengthLimitFilter(int limit) {
            this.limit = limit;
        }
        @Override
        public void insertString(FilterBypass fb, int offset, String string, javax.swing.text.AttributeSet attr) throws javax.swing.text.BadLocationException {
            if (string == null) return;
            if ((fb.getDocument().getLength() + string.length()) <= limit) {
                super.insertString(fb, offset, string, attr);
            } else {
                java.awt.Toolkit.getDefaultToolkit().beep();
            }
        }
        @Override
        public void replace(FilterBypass fb, int offset, int length, String text, javax.swing.text.AttributeSet attrs) throws javax.swing.text.BadLocationException {
            if (text == null) return;
            if ((fb.getDocument().getLength() + text.length() - length) <= limit) {
                super.replace(fb, offset, length, text, attrs);
            } else {
                java.awt.Toolkit.getDefaultToolkit().beep();
            }
        }
    }
}
