/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digielancer.component;

import digielancer.main.UserSession;
import digielancer.model.ServiceModel;

/**
 *
 * @author ASUS
 */
public class addProject extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addProject.class.getName());
    private int currentUserId;

    /**
     * Creates new form addProject
     */
    public addProject(java.awt.Frame parent, boolean modal, int currentUserId) {
        initComponents();
        this.currentUserId = currentUserId;
        loadServiceDropdown(currentUserId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        comboService = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtDeadline = new javax.swing.JFormattedTextField();
        kontakField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel1.setText("Project Baru");

        namaField.setText("Nama Klien");

        comboService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setBackground(new java.awt.Color(6, 141, 240));
        jButton1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan Project");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        try {
            txtDeadline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        kontakField.setText("Kontak klien");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 307, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(comboService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDeadline)
                                    .addComponent(kontakField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kontakField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboService, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String clientName = namaField.getText();
        String clientContact = kontakField.getText();
        String rawDate = txtDeadline.getText(); // User typed: "30-06-2026"

        // 3. Basic Validation: Prevent empty fields
        if (clientName.isEmpty() || clientContact.isEmpty() || rawDate.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Harap isi semua data!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 4. Translate Date and Save to Database
        try {
            // Convert dd-MM-yyyy to yyyy-MM-dd
            java.text.SimpleDateFormat userFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");
            java.text.SimpleDateFormat sqlFormat = new java.text.SimpleDateFormat("yyyy/MM/dd");

            java.util.Date parsedDate = userFormat.parse(rawDate);
            String sqlDateString = sqlFormat.format(parsedDate);
            
            Object selectedItem = comboService.getSelectedItem();
    
            // 2. Check: Is it actually a ServiceModel object?
            if (selectedItem instanceof digielancer.model.ServiceModel) {
                // It IS a ServiceModel! We can safely cast it now.
                digielancer.model.ServiceModel selectedService = (digielancer.model.ServiceModel) selectedItem;
                int serviceIdToSave = selectedService.getId();
                
                // 5. Send data to the DAO
                boolean isSuccess = digielancer.model.ProjectDAO.addProject(
                    this.currentUserId, 
                    serviceIdToSave, 
                    clientName, 
                    clientContact, 
                    sqlDateString
                );
                
                if (isSuccess) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Project berhasil ditambahkan!");
                    this.dispose(); // Close the popup window

                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan ke database.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // It was a String (like "Item 1" or "Select Service")
                javax.swing.JOptionPane.showMessageDialog(this, "Harap pilih Service yang valid dari dropdown!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
                return; // Stop the save process
            }
        } catch (java.text.ParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> comboService;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kontakField;
    private javax.swing.JTextField namaField;
    private javax.swing.JFormattedTextField txtDeadline;
    // End of variables declaration//GEN-END:variables
    
    private void loadServiceDropdown(int currentUserId) {
        // 1. Clear any default NetBeans placeholder items (like "Item 1, Item 2")
        comboService.removeAllItems();

        // 2. Fetch the data
        java.util.List<ServiceModel> services = digielancer.model.ServiceDAO.getServicesForUser(currentUserId);

        // 3. Add them to the dropdown
        for (ServiceModel service : services) {
            comboService.addItem(service);
        }
    }

}
