/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digielancer.component;

import digielancer.model.TaskModel;

/**
 *
 * @author ASUS
 */
public class deadlineReminder extends javax.swing.JPanel {

    /**
     * Creates new form deadlineReminder
     */
    public deadlineReminder() {
        initComponents();
    }

    public deadlineReminder(TaskModel task, long daysLeft) {
        initComponents();
        setData(task, daysLeft);
    }

    public void setData(TaskModel task, long daysLeft) {
        invoiceLabel.setText(task.getTitle());
        
        // Date formatting
        if (task.getDeadline() != null && !task.getDeadline().isEmpty() && !task.getDeadline().equals("null")) {
            try {
                java.time.LocalDate date = java.time.LocalDate.parse(task.getDeadline());
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("d MMM yyyy", java.util.Locale.ENGLISH);
                jLabel31.setText(date.format(formatter));
            } catch (Exception e) {
                jLabel31.setText(task.getDeadline());
            }
        } else {
            jLabel31.setText("-");
        }
        
        jLabel13.setText(daysLeft + " Hari Lagi!");
        
        // Style main panel and warning label based on deadline urgency
        if (daysLeft <= 3) {
            // Red scheme
            jPanel11.setBackground(new java.awt.Color(254, 242, 242));
            jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 165, 165)));
            jLabel13.setForeground(new java.awt.Color(220, 38, 38));
        } else {
            // Yellow scheme
            jPanel11.setBackground(new java.awt.Color(254, 253, 240));
            jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 224, 71)));
            jLabel13.setForeground(new java.awt.Color(202, 138, 4));
        }
        
        // Style priority badge independently based on task priority
        String priority = task.getPriority();
        if (priority == null) {
            priority = "Low";
        }
        jLabel16.setText(priority);
        if (priority.equalsIgnoreCase("High")) {
            jPanel7.setBackground(new java.awt.Color(254, 226, 226)); // light red
            jLabel16.setForeground(new java.awt.Color(220, 38, 38));  // dark red
        } else if (priority.equalsIgnoreCase("Medium")) {
            jPanel7.setBackground(new java.awt.Color(254, 243, 199)); // light amber/orange
            jLabel16.setForeground(new java.awt.Color(217, 119, 6));   // dark amber/orange
        } else { // Low or any other value
            jPanel7.setBackground(new java.awt.Color(209, 250, 229)); // light green
            jLabel16.setForeground(new java.awt.Color(5, 150, 105));   // dark green
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        invoiceLabel = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jPanel11.setBackground(new java.awt.Color(254, 242, 242));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 165, 165)));

        invoiceLabel.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        invoiceLabel.setText("API Integration");

        jLabel31.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(106, 114, 130));
        jLabel31.setText("8 Jun 2026");

        jPanel7.setBackground(new java.awt.Color(254, 226, 226));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(220, 38, 38));
        jLabel16.setText("High");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(220, 38, 38));
        jLabel13.setText("3 Hari Lagi!");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoiceLabel)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 445, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel31))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel invoiceLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
