/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digielancer.component;

import digielancer.main.UserSession;
import digielancer.main.KoneksiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dwi R.A. Kautsar
 */
public class keamananSett extends javax.swing.JPanel {

    /**
     * Creates new form keamananPanel
     */
    public keamananSett() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passLamaText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passBaruText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        konfPassTExt = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel1.setText("Ubah Password");

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setText("Password Lama");

        passLamaText.addActionListener(this::passLamaTextActionPerformed);

        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel3.setText("Password Baru");

        passBaruText.addActionListener(this::passBaruTextActionPerformed);

        jLabel4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel4.setText("Konfirmasi Password Baru");

        konfPassTExt.addActionListener(this::konfPassTExtActionPerformed);

        updateButton.setBackground(new java.awt.Color(6, 141, 240));
        updateButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update Password");
        updateButton.setBorderPainted(false);
        updateButton.setFocusPainted(false);
        updateButton.addActionListener(this::updateButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(passLamaText, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(passBaruText, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(konfPassTExt, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passLamaText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passBaruText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(konfPassTExt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passLamaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passLamaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passLamaTextActionPerformed

    private void passBaruTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passBaruTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passBaruTextActionPerformed

    private void konfPassTExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfPassTExtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konfPassTExtActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String passLama = passLamaText.getText();
        String passBaru = passBaruText.getText();
        String konfPass = konfPassTExt.getText();

        if (passLama.isEmpty() || passBaru.isEmpty() || konfPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom password harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!passBaru.equals(konfPass)) {
            JOptionPane.showMessageDialog(this, "Password baru dan konfirmasi tidak cocok!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Connection conn = KoneksiDB.configDB();
            
            // Pengecekan password lama
            String sqlCheck = "SELECT password_hash FROM USER WHERE id = ?";
            PreparedStatement pstCheck = conn.prepareStatement(sqlCheck);
            pstCheck.setInt(1, UserSession.getId());
            ResultSet rs = pstCheck.executeQuery();
            
            if (rs.next()) {
                String dbPass = rs.getString("password_hash");
                if (!dbPass.equals(passLama)) {
                    JOptionPane.showMessageDialog(this, "Password lama salah!", "Peringatan", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                // Pembaruan password baru
                String sqlUpdate = "UPDATE USER SET password_hash = ? WHERE id = ?";
                PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
                pstUpdate.setString(1, passBaru);
                pstUpdate.setInt(2, UserSession.getId());
                
                int updated = pstUpdate.executeUpdate();
                if (updated > 0) {
                    JOptionPane.showMessageDialog(this, "Password berhasil diperbarui!");
                    passLamaText.setText("");
                    passBaruText.setText("");
                    konfPassTExt.setText("");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField konfPassTExt;
    private javax.swing.JTextField passBaruText;
    private javax.swing.JTextField passLamaText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
