/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digielancer.component;

/**
 *
 * @author Dwi R.A. Kautsar
 */
public class layananSett extends javax.swing.JPanel {

    /**
     * Creates new form layananSett
     */
    public layananSett() {
        initComponents();
        loadDynamicServices();
    }

    private void loadDynamicServices() {
        this.removeAll();
        this.setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        this.setBackground(java.awt.Color.WHITE);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        jLabel1.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        this.add(jLabel1);
        this.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));

        javax.swing.JPanel servicesGrid = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        servicesGrid.setBackground(java.awt.Color.WHITE);
        servicesGrid.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        try {
            java.sql.Connection conn = digielancer.main.KoneksiDB.configDB();
            String sql = "SELECT id, service_name FROM MAIN_SERVICE WHERE user_id = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, digielancer.main.UserSession.getId());
            java.sql.ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                int serviceId = rs.getInt("id");
                String sName = rs.getString("service_name");
                
                javax.swing.JPanel itemPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));
                itemPanel.setBackground(new java.awt.Color(219, 234, 254));
                itemPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
                
                javax.swing.JLabel lbl = new javax.swing.JLabel(sName);
                lbl.setFont(new java.awt.Font("Inter", 1, 14));
                lbl.setForeground(new java.awt.Color(30, 64, 175));

                javax.swing.JButton btnHapus = new javax.swing.JButton("X");
                btnHapus.setBackground(new java.awt.Color(255, 51, 51));
                btnHapus.setForeground(java.awt.Color.WHITE);
                btnHapus.setMargin(new java.awt.Insets(2, 5, 2, 5));
                btnHapus.setFocusPainted(false);
                btnHapus.setBorderPainted(false);
                btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                btnHapus.addActionListener(e -> {
                    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                        "Apakah Anda yakin ingin menghapus layanan ini? Semua Add-ons terkait juga akan ikut terhapus.", 
                        "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
                    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                        try {
                            java.sql.PreparedStatement delAddon = conn.prepareStatement("DELETE FROM ADD_ON WHERE main_service_id=?");
                            delAddon.setInt(1, serviceId);
                            delAddon.executeUpdate();
                            
                            java.sql.PreparedStatement delMs = conn.prepareStatement("DELETE FROM MAIN_SERVICE WHERE id=?");
                            delMs.setInt(1, serviceId);
                            delMs.executeUpdate();
                            
                            loadDynamicServices(); // Reload UI
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                });
                
                itemPanel.add(lbl);
                itemPanel.add(btnHapus);
                servicesGrid.add(itemPanel);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        this.add(servicesGrid);
        this.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));
        
        editButton.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        this.add(editButton);
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pemwebPanel = new javax.swing.JPanel();
        pemweb = new javax.swing.JLabel();
        aplikasiPanel = new javax.swing.JPanel();
        aplikasiMobile = new javax.swing.JLabel();
        desainPanel = new javax.swing.JPanel();
        desainGrafis = new javax.swing.JLabel();
        motionPanel = new javax.swing.JPanel();
        motionGraphic = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel1.setText("Jenis Layanan Yang Ditawarkan");

        pemwebPanel.setBackground(new java.awt.Color(219, 234, 254));

        pemweb.setBackground(new java.awt.Color(254, 254, 254));
        pemweb.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        pemweb.setForeground(new java.awt.Color(30, 64, 175));
        pemweb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pemweb.setText("Pembuatan Web");

        javax.swing.GroupLayout pemwebPanelLayout = new javax.swing.GroupLayout(pemwebPanel);
        pemwebPanel.setLayout(pemwebPanelLayout);
        pemwebPanelLayout.setHorizontalGroup(
            pemwebPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemwebPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pemweb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pemwebPanelLayout.setVerticalGroup(
            pemwebPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemwebPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pemweb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        aplikasiPanel.setBackground(new java.awt.Color(219, 234, 254));

        aplikasiMobile.setBackground(new java.awt.Color(254, 254, 254));
        aplikasiMobile.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        aplikasiMobile.setForeground(new java.awt.Color(30, 64, 175));
        aplikasiMobile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aplikasiMobile.setText("Aplikasi Mobile");

        javax.swing.GroupLayout aplikasiPanelLayout = new javax.swing.GroupLayout(aplikasiPanel);
        aplikasiPanel.setLayout(aplikasiPanelLayout);
        aplikasiPanelLayout.setHorizontalGroup(
            aplikasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aplikasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aplikasiMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        aplikasiPanelLayout.setVerticalGroup(
            aplikasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aplikasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aplikasiMobile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desainPanel.setBackground(new java.awt.Color(219, 234, 254));

        desainGrafis.setBackground(new java.awt.Color(254, 254, 254));
        desainGrafis.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        desainGrafis.setForeground(new java.awt.Color(30, 64, 175));
        desainGrafis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desainGrafis.setText("Desain Grafis");

        javax.swing.GroupLayout desainPanelLayout = new javax.swing.GroupLayout(desainPanel);
        desainPanel.setLayout(desainPanelLayout);
        desainPanelLayout.setHorizontalGroup(
            desainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desainGrafis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        desainPanelLayout.setVerticalGroup(
            desainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desainGrafis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        motionPanel.setBackground(new java.awt.Color(219, 234, 254));

        motionGraphic.setBackground(new java.awt.Color(254, 254, 254));
        motionGraphic.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        motionGraphic.setForeground(new java.awt.Color(30, 64, 175));
        motionGraphic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        motionGraphic.setText("Motion Graphic");

        javax.swing.GroupLayout motionPanelLayout = new javax.swing.GroupLayout(motionPanel);
        motionPanel.setLayout(motionPanelLayout);
        motionPanelLayout.setHorizontalGroup(
            motionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(motionGraphic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        motionPanelLayout.setVerticalGroup(
            motionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(motionGraphic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editButton.setBackground(new java.awt.Color(6, 141, 240));
        editButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("Edit Layanan");
        editButton.setMaximumSize(new java.awt.Dimension(163, 48));
        editButton.setMinimumSize(new java.awt.Dimension(163, 48));
        editButton.setPreferredSize(new java.awt.Dimension(163, 48));
        editButton.addActionListener(this::editButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pemwebPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aplikasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(motionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aplikasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pemwebPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        // Inisialisasi frame edit layanan
        editLayananFrame editFrame = new editLayananFrame();
        
        // Penentuan posisi agar muncul di tengah layar
        editFrame.setLocationRelativeTo(null);
        
        // Pengaturan tutup jendela khusus untuk popup
        editFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Penampilan frame ke layar
        editFrame.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aplikasiMobile;
    private javax.swing.JPanel aplikasiPanel;
    private javax.swing.JLabel desainGrafis;
    private javax.swing.JPanel desainPanel;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel motionGraphic;
    private javax.swing.JPanel motionPanel;
    private javax.swing.JLabel pemweb;
    private javax.swing.JPanel pemwebPanel;
    // End of variables declaration//GEN-END:variables
}
