/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digielancer.component;

/**
 *
 * @author ilyas
 */
public class MenuInvoice extends javax.swing.JPanel {

    /**
     * Creates new form MenuInvoice
     */
    public MenuInvoice() {
        initComponents();
        switchContent(new InvoicePanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InvoiceNav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonNota = new javax.swing.JButton();
        jButtonHistory = new javax.swing.JButton();
        InvoiceMenu = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("Generator & History Nota");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel2.setText("Buat nota baru dan lihat riwayat invoice");

        jButtonNota.setBackground(new java.awt.Color(6, 141, 240));
        jButtonNota.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jButtonNota.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNota.setText("Buat Nota Baru");
        jButtonNota.addActionListener(this::jButtonNotaActionPerformed);

        jButtonHistory.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jButtonHistory.setForeground(new java.awt.Color(51, 51, 51));
        jButtonHistory.setText("History Invoice");

        javax.swing.GroupLayout InvoiceNavLayout = new javax.swing.GroupLayout(InvoiceNav);
        InvoiceNav.setLayout(InvoiceNavLayout);
        InvoiceNavLayout.setHorizontalGroup(
            InvoiceNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoiceNavLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(InvoiceNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InvoiceNavLayout.createSequentialGroup()
                        .addComponent(jButtonNota)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHistory))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        InvoiceNavLayout.setVerticalGroup(
            InvoiceNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoiceNavLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(InvoiceNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNota, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(InvoiceNav, java.awt.BorderLayout.PAGE_START);

        InvoiceMenu.setLayout(new java.awt.BorderLayout());
        add(InvoiceMenu, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotaActionPerformed

        // TODO add your handling code here:
        switchContent(new InvoicePanel());
    }//GEN-LAST:event_jButtonNotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InvoiceMenu;
    private javax.swing.JPanel InvoiceNav;
    private javax.swing.JButton jButtonHistory;
    private javax.swing.JButton jButtonNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

public void switchContent(javax.swing.JPanel panel) {
        // 1. Remove everything currently in the main container
        InvoiceMenu.removeAll();

        // 2. Add the new panel to the center
        InvoiceMenu.add(panel, java.awt.BorderLayout.CENTER);

        // 3. Force the UI to refresh and show the new panel
        InvoiceMenu.revalidate();
        InvoiceMenu.repaint();
    }
    
    private void setActiveMenu(javax.swing.JButton activeButton) {
        // 1. Put all your sidebar buttons in an array
        // (Make sure these variable names match what you named them in NetBeans)
        javax.swing.JButton[] menuButtons = {
            jButtonNota, jButtonHistory
        };

        // 2. Define your colors based on your image
        java.awt.Color defaultText = new java.awt.Color(153, 161, 175); // Grey text
        java.awt.Color activeBg = new java.awt.Color(6, 141, 240);     // Bright Blue
        java.awt.Color activeText = new java.awt.Color(248, 250, 252);               // White text

        // 3. Loop through every button
        for (javax.swing.JButton btn : menuButtons) {
            if (btn == activeButton) {
                // Turn ON the highlight for the clicked button
                btn.setBackground(activeBg);
                btn.setForeground(activeText);
                btn.setContentAreaFilled(true); // Fill the background with blue
            } else {
                // Turn OFF the highlight for the rest
                btn.setForeground(defaultText);
                btn.setContentAreaFilled(false); // Make background transparent again
            }
        }
    }
}
