/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digielancer.component;

import digielancer.model.ProjectDAO.NewestProjectDTO;

/**
 *
 * @author ASUS
 */
public class newestProject extends javax.swing.JPanel {

    /**
     * Creates new form newestProject
     */
    public newestProject() {
        initComponents();
    }

    public newestProject(NewestProjectDTO project) {
        initComponents();
        setData(project);
    }

    public void setData(NewestProjectDTO project) {
        clientName.setText(project.getClientName());
        serviceLabel.setText(project.getServiceName());
        
        // Date formatting
        if (project.getDeadline() != null && !project.getDeadline().isEmpty() && !project.getDeadline().equals("null")) {
            try {
                java.time.LocalDate date = java.time.LocalDate.parse(project.getDeadline());
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("d MMM yyyy", java.util.Locale.ENGLISH);
                deadline.setText(date.format(formatter));
            } catch (Exception e) {
                deadline.setText(project.getDeadline());
            }
        } else {
            deadline.setText("-");
        }
        
        status.setText(project.isActive() ? "Aktif" : "Selesai");
        if (project.isActive()) {
            jPanel10.setBackground(new java.awt.Color(219, 234, 254)); // blue background
            status.setForeground(new java.awt.Color(30, 64, 175));      // blue text
        } else {
            jPanel10.setBackground(new java.awt.Color(209, 250, 229)); // green background
            status.setForeground(new java.awt.Color(6, 95, 70));        // green text
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientName = new javax.swing.JLabel();
        serviceLabel = new javax.swing.JLabel();
        deadline = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        status = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        clientName.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        clientName.setText("API Integration");

        serviceLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        serviceLabel.setForeground(new java.awt.Color(106, 114, 130));
        serviceLabel.setText("Connect API");

        deadline.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        deadline.setForeground(new java.awt.Color(106, 114, 130));
        deadline.setText("3 Jun 2024");

        jPanel10.setBackground(new java.awt.Color(219, 234, 254));

        status.setBackground(new java.awt.Color(255, 255, 255));
        status.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(30, 64, 175));
        status.setText("Aktif");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(status)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(status)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientName)
                            .addComponent(serviceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deadline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clientName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deadline)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientName;
    private javax.swing.JLabel deadline;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JLabel serviceLabel;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
