/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digielancer.component;

import digielancer.model.ProjectDAO.NewestInvoiceDTO;

/**
 *
 * @author ASUS
 */
public class newestInvoice extends javax.swing.JPanel {

    /**
     * Creates new form newestInvoice
     */
    public newestInvoice() {
        initComponents();
    }

    public newestInvoice(NewestInvoiceDTO invoice) {
        initComponents();
        setData(invoice);
    }

    public void setData(NewestInvoiceDTO invoice) {
        // Display the project's client name
        projectLabel.setText(invoice.getClientName());
        
        // Amount formatting (e.g. Rp 8.000.000)
        double total = invoice.getTotalAmount();
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance(new java.util.Locale("id", "ID"));
        ammount.setText("Rp " + nf.format(total));
        
        // Date formatting (generatedDate)
        if (invoice.getGeneratedDate() != null && !invoice.getGeneratedDate().isEmpty() && !invoice.getGeneratedDate().equals("null")) {
            try {
                java.time.LocalDate date = java.time.LocalDate.parse(invoice.getGeneratedDate());
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("d MMM yyyy", java.util.Locale.ENGLISH);
                deadlineProject.setText(date.format(formatter));
            } catch (Exception e) {
                deadlineProject.setText(invoice.getGeneratedDate());
            }
        } else {
            deadlineProject.setText("-");
        }
        
        // Status badge styling
        String statusText = invoice.getStatus();
        if (statusText == null) {
            statusText = "Pending";
        }
        jLabel37.setText(statusText);
        
        if (statusText.equalsIgnoreCase("Paid") || statusText.equalsIgnoreCase("Lunas") || statusText.equalsIgnoreCase("Selesai")) {
            statusLabel.setBackground(new java.awt.Color(209, 250, 229)); // light green
            jLabel37.setForeground(new java.awt.Color(5, 150, 105));   // dark green
        } else if (statusText.equalsIgnoreCase("Pending")) {
            statusLabel.setBackground(new java.awt.Color(254, 243, 199)); // light amber/orange
            jLabel37.setForeground(new java.awt.Color(217, 119, 6));   // dark amber/orange
        } else {
            statusLabel.setBackground(new java.awt.Color(254, 226, 226)); // light red
            jLabel37.setForeground(new java.awt.Color(220, 38, 38));  // dark red
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectLabel = new javax.swing.JLabel();
        deadlineProject = new javax.swing.JLabel();
        statusLabel = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        ammount = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        projectLabel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        projectLabel.setText("CMotion");

        deadlineProject.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        deadlineProject.setForeground(new java.awt.Color(106, 114, 130));
        deadlineProject.setText("3 Jun 2024");

        statusLabel.setBackground(new java.awt.Color(254, 243, 199));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(217, 119, 6));
        jLabel37.setText("Pending");

        javax.swing.GroupLayout statusLabelLayout = new javax.swing.GroupLayout(statusLabel);
        statusLabel.setLayout(statusLabelLayout);
        statusLabelLayout.setHorizontalGroup(
            statusLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addContainerGap())
        );
        statusLabelLayout.setVerticalGroup(
            statusLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addContainerGap())
        );

        ammount.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        ammount.setForeground(new java.awt.Color(6, 141, 240));
        ammount.setText("Rp 8.000.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deadlineProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectLabel)
                            .addComponent(ammount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ammount)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deadlineProject)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ammount;
    private javax.swing.JLabel deadlineProject;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JPanel statusLabel;
    // End of variables declaration//GEN-END:variables
}
