/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digielancer.component;

import digielancer.main.UserSession;
import digielancer.main.KoneksiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author Dwi R.A. Kautsar
 */
public class profilSett extends javax.swing.JPanel {

    /**
     * Creates new form profilSettings
     */
    public profilSett() {
        initComponents();
        loadUserData();
    }

    private void loadUserData() {
        if(UserSession.getId() != 0) {
            namaTextField.setText(UserSession.getBusinessName());
            namaTextField.setForeground(Color.BLACK);
            emailTextField.setText(UserSession.getEmail());
            emailTextField.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel1.setText("Informasi Profil");

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setText("Nama Lengkap / Bisnis");

        namaTextField.setForeground(new java.awt.Color(204, 204, 204));
        namaTextField.setText("Masukkan Nama Anda");
        namaTextField.setMaximumSize(new java.awt.Dimension(630, 50));
        namaTextField.setMinimumSize(new java.awt.Dimension(630, 50));
        namaTextField.setPreferredSize(new java.awt.Dimension(630, 50));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel3.setText("Email");

        emailTextField.setForeground(new java.awt.Color(204, 204, 204));
        emailTextField.setText("Masukkan Email Anda");
        emailTextField.setMaximumSize(new java.awt.Dimension(630, 50));
        emailTextField.setMinimumSize(new java.awt.Dimension(630, 50));
        emailTextField.setPreferredSize(new java.awt.Dimension(630, 50));
        emailTextField.addActionListener(this::emailTextFieldActionPerformed);

        jButton1.setBackground(new java.awt.Color(6, 141, 242));
        jButton1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan Perubahan");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(189, 48));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Pengambilan input pengguna
        String newName = namaTextField.getText().trim();
        String newEmail = emailTextField.getText().trim();
        
        if(newName.isEmpty() || newEmail.isEmpty() || newName.equals("Masukkan Nama Anda") || newEmail.equals("Masukkan Email Anda")) {
            JOptionPane.showMessageDialog(this, "Nama dan Email tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            // Persiapan koneksi dan query update
            Connection conn = KoneksiDB.configDB();
            String sql = "UPDATE USER SET business_name=?, email=? WHERE id=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, newName);
            pst.setString(2, newEmail);
            pst.setInt(3, UserSession.getId());
            
            // Eksekusi query
            int updated = pst.executeUpdate();
            if(updated > 0) {
                // Pembaruan sesi lokal jika berhasil
                UserSession.setSession(UserSession.getId(), newName, newEmail);
                JOptionPane.showMessageDialog(this, "Profil berhasil diperbarui!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui profil: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField namaTextField;
    // End of variables declaration//GEN-END:variables
}
