/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digielancer.component;

import digielancer.main.Navbar;
import digielancer.model.ProjectModel;

/**
 *
 * @author ASUS
 */
public class ProjectPanel extends javax.swing.JPanel {

    private int projectId;
    /**
     * Creates new form ProjectPanel
     */
    public ProjectPanel(ProjectModel project, final Navbar mainApp) {
        initComponents();
        
        this.projectId = project.getId();
        
        // 1. Set your visual labels (ensure you have these named in your designer)
        labelKlien.setText(project.getClientName());
        labelDeadline.setText("Deadline: " + project.getDeadline());
        
        // Check active status
        if (project.isActive()) {
            activeLabel.setText("Aktif");
            activeLabel.setForeground(new java.awt.Color(30, 64, 175)); // Blue
            activeContainer.setBackground(new java.awt.Color(219, 234, 254)); // Light Blue
        } else {
            activeLabel.setText("Selesai");
            activeLabel.setForeground(new java.awt.Color(22, 163, 74)); // Green
            activeContainer.setBackground(new java.awt.Color(220, 252, 231)); // Light Green
        }
        
        // 2. Lock the size so they don't stretch weirdly in the horizontal list
        this.setMinimumSize(new java.awt.Dimension(250, 110));
        this.setMaximumSize(new java.awt.Dimension(250, 110));
        this.setPreferredSize(new java.awt.Dimension(250, 110));
        
        // 3. Make the entire card clickable!
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // When clicked, tell the Main Dashboard to load THIS project's board!
                mainApp.switchContent(new ProjectManagement(mainApp, projectId));
            }
            
            // Optional UX Polish: Change cursor to hand when hovering
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelKlien = new javax.swing.JLabel();
        labelService = new javax.swing.JLabel();
        activeContainer = new javax.swing.JPanel();
        activeLabel = new javax.swing.JLabel();
        labelDeadline = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        labelKlien.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        labelKlien.setText("CMotion");

        labelService.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        labelService.setText("Web Development");

        activeContainer.setBackground(new java.awt.Color(219, 234, 254));

        activeLabel.setBackground(new java.awt.Color(255, 255, 255));
        activeLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        activeLabel.setForeground(new java.awt.Color(30, 64, 175));
        activeLabel.setText("Aktif");

        javax.swing.GroupLayout activeContainerLayout = new javax.swing.GroupLayout(activeContainer);
        activeContainer.setLayout(activeContainerLayout);
        activeContainerLayout.setHorizontalGroup(
            activeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activeContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(activeLabel)
                .addContainerGap())
        );
        activeContainerLayout.setVerticalGroup(
            activeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activeContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(activeLabel)
                .addContainerGap())
        );

        labelDeadline.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        labelDeadline.setText("2026-06-08");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digielancer/assets/editIcon.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digielancer/assets/closeIcon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelService)
                    .addComponent(labelKlien)
                    .addComponent(labelDeadline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(activeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(40, 40, 40)
                        .addComponent(activeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelKlien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelService)
                        .addGap(24, 24, 24)
                        .addComponent(labelDeadline)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activeContainer;
    private javax.swing.JLabel activeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelDeadline;
    private javax.swing.JLabel labelKlien;
    private javax.swing.JLabel labelService;
    // End of variables declaration//GEN-END:variables
}
