/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digielancer.component;

/**
 *
 * @author Dwi R.A. Kautsar
 */
public class settingList extends javax.swing.JPanel {

    /**
     * Creates new form settingList
     */
    public settingList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profileButton = new javax.swing.JButton();
        layananButton = new javax.swing.JButton();
        tarifButton = new javax.swing.JButton();
        keamananButton = new javax.swing.JButton();
        tentangButton = new javax.swing.JButton();
        panelKonten = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setText("Pengaturan");

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setText("Kelola profil dan preferensi akun Anda");

        profileButton.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        profileButton.setText("Profil");
        profileButton.setBorderPainted(false);
        profileButton.setFocusPainted(false);
        profileButton.setMaximumSize(new java.awt.Dimension(256, 48));
        profileButton.setMinimumSize(new java.awt.Dimension(256, 48));
        profileButton.setPreferredSize(new java.awt.Dimension(256, 48));
        profileButton.addActionListener(this::profileButtonActionPerformed);

        layananButton.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        layananButton.setText("Jenis Layanan");
        layananButton.setBorderPainted(false);
        layananButton.setFocusPainted(false);
        layananButton.setMaximumSize(new java.awt.Dimension(256, 48));
        layananButton.setMinimumSize(new java.awt.Dimension(256, 48));
        layananButton.setPreferredSize(new java.awt.Dimension(256, 48));
        layananButton.addActionListener(this::layananButtonActionPerformed);

        tarifButton.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        tarifButton.setText("Tarif & Add-ons");
        tarifButton.setBorderPainted(false);
        tarifButton.setFocusPainted(false);
        tarifButton.setMaximumSize(new java.awt.Dimension(256, 48));
        tarifButton.setMinimumSize(new java.awt.Dimension(256, 48));
        tarifButton.setPreferredSize(new java.awt.Dimension(256, 48));
        tarifButton.addActionListener(this::tarifButtonActionPerformed);

        keamananButton.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        keamananButton.setText("Keamanan");
        keamananButton.setBorderPainted(false);
        keamananButton.setFocusPainted(false);
        keamananButton.setMaximumSize(new java.awt.Dimension(256, 48));
        keamananButton.setMinimumSize(new java.awt.Dimension(256, 48));
        keamananButton.setPreferredSize(new java.awt.Dimension(256, 48));
        keamananButton.addActionListener(this::keamananButtonActionPerformed);

        tentangButton.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        tentangButton.setText("Tentang");
        tentangButton.setBorderPainted(false);
        tentangButton.setFocusPainted(false);
        tentangButton.setMaximumSize(new java.awt.Dimension(256, 48));
        tentangButton.setMinimumSize(new java.awt.Dimension(256, 48));
        tentangButton.setPreferredSize(new java.awt.Dimension(256, 48));
        tentangButton.addActionListener(this::tentangButtonActionPerformed);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(layananButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarifButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keamananButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tentangButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layananButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarifButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keamananButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tentangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKonten.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelKonten, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(panelKonten, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        // TODO add your handling code here:
        switchContent(new profilSett());
    }//GEN-LAST:event_profileButtonActionPerformed

    private void layananButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layananButtonActionPerformed
        // TODO add your handling code here:
        switchContent(new layananSett());
    }//GEN-LAST:event_layananButtonActionPerformed

    private void tarifButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifButtonActionPerformed
        // TODO add your handling code here:
        switchContent(new tarifSett());
    }//GEN-LAST:event_tarifButtonActionPerformed

    private void keamananButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keamananButtonActionPerformed
        // TODO add your handling code here:
        switchContent(new keamananSett());
    }//GEN-LAST:event_keamananButtonActionPerformed

    private void tentangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangButtonActionPerformed
        // TODO add your handling code here:
        switchContent(new tentangSett());
    }//GEN-LAST:event_tentangButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton keamananButton;
    private javax.swing.JButton layananButton;
    private javax.swing.JPanel panelKonten;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton tarifButton;
    private javax.swing.JButton tentangButton;
    // End of variables declaration//GEN-END:variables

    public void switchContent(javax.swing.JPanel panel) {
        // 1. Remove everything currently in the main container
        panelKonten.removeAll();

        // 2. Add the new panel to the center
        panelKonten.add(panel, java.awt.BorderLayout.CENTER);

        // 3. Force the UI to refresh and show the new panel
        panelKonten.revalidate();
        panelKonten.repaint();
    }
    
    private void setActiveMenu(javax.swing.JButton activeButton) {
        // 1. Put all your sidebar buttons in an array
        // (Make sure these variable names match what you named them in NetBeans)
        javax.swing.JButton[] menuButtons = {
            profileButton, layananButton, tarifButton, keamananButton, tentangButton
        };

        // 2. Define your colors based on your image
        java.awt.Color defaultText = new java.awt.Color(153, 161, 175); // Grey text
        java.awt.Color activeBg = new java.awt.Color(6, 141, 240);     // Bright Blue
        java.awt.Color activeText = new java.awt.Color(248, 250, 252);               // White text

        // 3. Loop through every button
        for (javax.swing.JButton btn : menuButtons) {
            if (btn == activeButton) {
                // Turn ON the highlight for the clicked button
                btn.setBackground(activeBg);
                btn.setForeground(activeText);
                btn.setContentAreaFilled(true); // Fill the background with blue
            } else {
                // Turn OFF the highlight for the rest
                btn.setForeground(defaultText);
                btn.setContentAreaFilled(false); // Make background transparent again
            }
        }
    }
}
