/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digielancer.component;

import digielancer.model.TaskModel;
import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class taskCard extends javax.swing.JPanel {

    private int taskID;
    private digielancer.component.ProjectManagement parentBoard;
    /**
     * Creates new form taskCard
     */
    public taskCard(TaskModel task, digielancer.component.ProjectManagement parentBoard) {
        initComponents();
        
        this.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 100));
        
        this.taskID = task.getId();
        this.parentBoard = parentBoard;
        
        // Push the database text into the labels you dragged onto the screen
        taskTitle.setText(task.getTitle());
        taskDL.setText("Deadline: " + task.getDeadline());
        labelPriority.setText(task.getPriority());
        
        // Optional: Change the priority text color based on the value
        if (task.getPriority().equals("High")) {
            labelPriority.setForeground(new Color(255, 255, 255));
            panelLabel.setBackground(new Color(239, 68, 68));
        } else if (task.getPriority().equals("Medium")) {
            labelPriority.setForeground(new Color(243, 156, 18)); // Orange
        } else {
            labelPriority.setForeground(new Color(46, 204, 113)); // Green
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskTitle = new javax.swing.JLabel();
        taskDesc = new javax.swing.JLabel();
        taskDL = new javax.swing.JLabel();
        panelLabel = new javax.swing.JPanel();
        labelPriority = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        taskTitle.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        taskTitle.setText("API Integration");

        taskDesc.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        taskDesc.setText("Connect API");

        taskDL.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        taskDL.setText("2026-06-08");

        panelLabel.setBackground(new java.awt.Color(239, 68, 68));

        labelPriority.setBackground(new java.awt.Color(255, 255, 255));
        labelPriority.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        labelPriority.setForeground(new java.awt.Color(255, 255, 255));
        labelPriority.setText("High");

        javax.swing.GroupLayout panelLabelLayout = new javax.swing.GroupLayout(panelLabel);
        panelLabel.setLayout(panelLabelLayout);
        panelLabelLayout.setHorizontalGroup(
            panelLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPriority)
                .addContainerGap())
        );
        panelLabelLayout.setVerticalGroup(
            panelLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPriority)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digielancer/assets/editIcon.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digielancer/assets/closeIcon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskDL)
                    .addComponent(taskTitle)
                    .addComponent(taskDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(taskTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(taskDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(taskDL))
                    .addComponent(panelLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelPriority;
    private javax.swing.JPanel panelLabel;
    private javax.swing.JLabel taskDL;
    private javax.swing.JLabel taskDesc;
    private javax.swing.JLabel taskTitle;
    // End of variables declaration//GEN-END:variables
}
