/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digielancer.main;


import digielancer.component.Dashboard;
import digielancer.component.MenuInvoice;
import digielancer.component.ProjectList;
import digielancer.component.settingList;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class Navbar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Navbar.class.getName());

    /**
     * Creates new form Navbar
     */
    public Navbar() {
        initComponents();
        
        // faviconn
        java.net.URL iconURL = getClass().getResource("/digielancer/assets/favicon-64.png");
        ImageIcon appIcon = new ImageIcon(iconURL);
        setIconImage(appIcon.getImage());
        
        // sessionn login
        if (UserSession.getBusinessName() != null) {
            jLabel4.setText(UserSession.getBusinessName());
            jLabel3.setText(UserSession.getEmail());
        }
        
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    
    public class MyForm extends javax.swing.JFrame {
        public MyForm() {
            initComponents();
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/favicon-64.png"));
            this.setIconImage(icon.getImage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonDashboard = new javax.swing.JButton();
        jButtonProjects = new javax.swing.JButton();
        jButtonInvoices = new javax.swing.JButton();
        jButtonSettings = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(5, 27, 60));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Digi Elancer");

        jLabel2.setBackground(new java.awt.Color(153, 161, 175));
        jLabel2.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 161, 175));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("GoDigi BETA");

        jButtonDashboard.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButtonDashboard.setForeground(new java.awt.Color(153, 161, 175));
        jButtonDashboard.setText("Dashboard");
        jButtonDashboard.setBorderPainted(false);
        jButtonDashboard.setContentAreaFilled(false);
        jButtonDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDashboard.setFocusPainted(false);
        jButtonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonDashboard.addActionListener(this::jButtonDashboardActionPerformed);

        jButtonProjects.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButtonProjects.setForeground(new java.awt.Color(153, 161, 175));
        jButtonProjects.setText("Projects");
        jButtonProjects.setBorderPainted(false);
        jButtonProjects.setContentAreaFilled(false);
        jButtonProjects.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonProjects.setFocusPainted(false);
        jButtonProjects.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonProjects.addActionListener(this::jButtonProjectsActionPerformed);

        jButtonInvoices.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButtonInvoices.setForeground(new java.awt.Color(153, 161, 175));
        jButtonInvoices.setText("Invoices");
        jButtonInvoices.setBorderPainted(false);
        jButtonInvoices.setContentAreaFilled(false);
        jButtonInvoices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInvoices.setFocusPainted(false);
        jButtonInvoices.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonInvoices.addActionListener(this::jButtonInvoicesActionPerformed);

        jButtonSettings.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButtonSettings.setForeground(new java.awt.Color(153, 161, 175));
        jButtonSettings.setText("Settings");
        jButtonSettings.setBorderPainted(false);
        jButtonSettings.setContentAreaFilled(false);
        jButtonSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSettings.setFocusPainted(false);
        jButtonSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSettings.addActionListener(this::jButtonSettingsActionPerformed);

        jButtonLogout.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(153, 161, 175));
        jButtonLogout.setText("Logout");
        jButtonLogout.setBorderPainted(false);
        jButtonLogout.setContentAreaFilled(false);
        jButtonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogout.setFocusPainted(false);
        jButtonLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonLogout.addActionListener(this::jButtonLogoutActionPerformed);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 161, 175));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("firdiansyahmf.04@gmail.com");

        jLabel4.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Ansyah Creative");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonLogout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSettings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonInvoices, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonProjects, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(63, 63, 63)
                .addComponent(jButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(22, 22, 22))
        );

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        mainContentPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboardActionPerformed
        // TODO add your handling code here:
        setActiveMenu(jButtonDashboard); 
        
        switchContent(new Dashboard());
    }//GEN-LAST:event_jButtonDashboardActionPerformed

    private void jButtonProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjectsActionPerformed
        // TODO add your handling code here:
        setActiveMenu(jButtonProjects);
                
        switchContent(new ProjectList());
    }//GEN-LAST:event_jButtonProjectsActionPerformed

    private void jButtonInvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvoicesActionPerformed
        // TODO add your handling code here:
        
        setActiveMenu(jButtonInvoices);
        switchContent(new MenuInvoice());
    }//GEN-LAST:event_jButtonInvoicesActionPerformed

    private void jButtonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsActionPerformed
        // TODO add your handling code here:
        setActiveMenu(jButtonSettings);
        
        switchContent(new settingList());
    }//GEN-LAST:event_jButtonSettingsActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar?", "Konfirmasi Logout",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            UserSession.clearSession();
            this.dispose();
            java.awt.EventQueue.invokeLater(() -> {
                new LoginScreen().setVisible(true);
            });
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Navbar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDashboard;
    private javax.swing.JButton jButtonInvoices;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonProjects;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables

    public void switchContent(javax.swing.JPanel panel) {
        // 1. Remove everything currently in the main container
        mainContentPanel.removeAll();

        // 2. Add the new panel to the center
        mainContentPanel.add(panel, java.awt.BorderLayout.CENTER);

        // 3. Force the UI to refresh and show the new panel
        mainContentPanel.revalidate();
        mainContentPanel.repaint();
    }
    
    private void setActiveMenu(javax.swing.JButton activeButton) {
        // 1. Put all your sidebar buttons in an array
        // (Make sure these variable names match what you named them in NetBeans)
        javax.swing.JButton[] menuButtons = {
            jButtonDashboard, jButtonProjects, jButtonInvoices, jButtonSettings
        };

        // 2. Define your colors based on your image
        java.awt.Color defaultText = new java.awt.Color(153, 161, 175); // Grey text
        java.awt.Color activeBg = new java.awt.Color(6, 141, 240);     // Bright Blue
        java.awt.Color activeText = new java.awt.Color(248, 250, 252);               // White text

        // 3. Loop through every button
        for (javax.swing.JButton btn : menuButtons) {
            if (btn == activeButton) {
                // Turn ON the highlight for the clicked button
                btn.setBackground(activeBg);
                btn.setForeground(activeText);
                btn.setContentAreaFilled(true); // Fill the background with blue
            } else {
                // Turn OFF the highlight for the rest
                btn.setForeground(defaultText);
                btn.setContentAreaFilled(false); // Make background transparent again
            }
        }
    }
}
